"""Fields login added to User

Revision ID: 6d26ab67f639
Revises: d7cfc850a14d
Create Date: 2020-08-16 20:08:26.321668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d26ab67f639'
down_revision = 'd7cfc850a14d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'restaurant', type_='foreignkey')
    op.create_foreign_key(None, 'restaurant', 'address', ['address_id'], ['id'])
    op.create_foreign_key(None, 'restaurant', 'user', ['user_id'], ['id'])
    op.drop_column('restaurant', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant', sa.Column('address', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'restaurant', type_='foreignkey')
    op.drop_constraint(None, 'restaurant', type_='foreignkey')
    op.create_foreign_key(None, 'restaurant', 'address', ['address'], ['id'])
    # ### end Alembic commands ###
