"""empty message

Revision ID: ce43ed398ea5
Revises: d306f5233db7
Create Date: 2020-08-12 13:11:31.779260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce43ed398ea5'
down_revision = 'd306f5233db7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant', sa.Column('address_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'restaurant', type_='foreignkey')
    op.create_foreign_key(None, 'restaurant', 'address', ['address_id'], ['id'])
    op.create_foreign_key(None, 'restaurant', 'user', ['user_id'], ['id'])
    op.drop_column('restaurant', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant', sa.Column('address', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'restaurant', type_='foreignkey')
    op.drop_constraint(None, 'restaurant', type_='foreignkey')
    op.create_foreign_key(None, 'restaurant', 'address', ['address'], ['id'])
    op.drop_column('restaurant', 'address_id')
    # ### end Alembic commands ###
